"""Propose figure_value CANDIDATES for human verification against the crops.

    python -m scripts.propose_figure_values --config configs/scale500.yaml --n 14

Why this is a separate script from build_gold.py, and not a category inside it:
build_gold SELECTS facts from the knowledge graph, so its answers and evidence are
already known and only the phrasing is generated. That discipline is what makes the
gold set trustworthy, and it cannot produce figure_value items here — the closed
schema has no value-relation (`measured_by` names the *method*, not the value), so a
table's numbers never become edges. Phase 6A hit this and hand-built 4 items; the
500-page KG yields only 3, for the same structural reason.

So these are **proposals, not gold**. The value is read off the table's OCR, which
phase 9 showed has the right digits in the wrong grid, and the caption. Every record
is emitted with `needs_value_verification: true` and its crop path, and NOTHING here
should enter the gold set until a human has checked the value against the image.

Deliberately NOT generated by the vision model. Using gpt-4o vision to author the gold
answers for the category that measures gpt-4o vision would let the system under test
mark its own homework, and any VQA "win" would be circular. The crop image is the
authority, and the authority is read by a person.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

from platform_core.config import AppConfig
from platform_core.llm.openai_client import OpenAIClient
from platform_core.stores.chunk_store import SQLiteChunkStore
from platform_core.types import RegionType

R = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace("\\", "/")
DEFAULT_CONFIG = R + "/configs/scale500.yaml"
IN_PRICE, OUT_PRICE = 0.15 / 1e6, 0.60 / 1e6

SYSTEM = ("You write exam questions about values reported in a scientific table. "
          "You return strict JSON and never invent numbers that are not in the text.")
USER = """Below is the caption and the OCR'd text of one table from a scientific paper.
The OCR has lost the table's grid: the values are correct-ish but their row/column
placement is unreliable.

CAPTION: {CAP}

OCR TEXT: {OCR}

Pick ONE clearly-labelled numeric value and write a question whose answer is that value.
Requirements:
- The question must name the row/column label in words that appear in the caption or OCR
  above. Do NOT invent a category, group, or condition that is not written above.
- The question must be answerable ONLY by reading this table.
- Report the value exactly as it appears in the OCR.

Return ONLY JSON: {"question": "...", "value": "...", "label": "<the row/column label you used>"}
If no value is clearly labelled, return {"question": "", "value": "", "label": ""}."""


def flat(s, n=1200):
    return " ".join((s or "").split())[:n]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=DEFAULT_CONFIG)
    ap.add_argument("--n", type=int, default=14)
    args = ap.parse_args()

    cfg = AppConfig.from_yaml(args.config)
    print(cfg.describe())
    store = SQLiteChunkStore(cfg.paths.chunk_db)

    # Only tables that are actually reachable: a caption (the retrieval route that works)
    # and enough OCR to contain a value. A proposal on an unretrievable table would
    # measure retrieval, not reading.
    tables = [c for c in store.iter_chunks([RegionType.TABLE])
              if c.image_path and c.caption_id and len(c.text.strip()) >= 120
              and any(ch.isdigit() for ch in c.text)]
    tables.sort(key=lambda c: c.chunk_id)
    stride = max(1, len(tables) // max(1, args.n * 2))
    picked = tables[::stride]
    print(f"\n{len(tables)} captioned table crops with numeric OCR; "
          f"proposing from {min(args.n, len(picked))} of them")

    llm = OpenAIClient(model="gpt-4o-mini")
    out: list[dict] = []
    for c in picked:
        if len(out) >= args.n:
            break
        try:
            cap = flat(store.get(c.caption_id).text, 300)
        except KeyError:
            continue
        try:
            r = llm.complete_json(SYSTEM, USER.replace("{CAP}", cap)
                                  .replace("{OCR}", flat(c.text)))
        except Exception as exc:
            print(f"  ! {c.chunk_id}: {type(exc).__name__}")
            continue
        if not (isinstance(r, dict) and r.get("question") and r.get("value")):
            continue
        # the proposed value must actually occur in the OCR — the one check that can be
        # made without a human, and it catches an invented number
        digits = "".join(ch for ch in str(r["value"]) if ch.isdigit())
        ocr_digits = "".join(ch for ch in c.text if ch.isdigit())
        out.append({
            "question": r["question"].strip(),
            "category": "figure_value",
            "proposed_answer": str(r["value"]).strip(),
            "row_label": str(r.get("label", "")).strip(),
            "supporting_chunk_ids": [c.chunk_id],
            "caption_id": c.caption_id,
            "crop_path": c.image_path,
            "caption": cap,
            "ocr_text": flat(c.text, 700),
            "value_digits_present_in_ocr": bool(digits) and digits in ocr_digits,
            "needs_value_verification": True,
            "provenance": "table-ocr-proposal (NOT graph-selected, NOT vision-generated)",
        })

    os.makedirs(cfg.paths.reports_dir, exist_ok=True)
    p = os.path.join(cfg.paths.reports_dir, "figure_value_candidates.jsonl")
    with open(p, "w", encoding="utf-8") as f:
        for r in out:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    ok = sum(1 for r in out if r["value_digits_present_in_ocr"])
    u = llm.total_usage
    print(f"\nwrote {len(out)} candidates -> {p}")
    print(f"  proposed value's digits found in the table's OCR: {ok}/{len(out)} "
          f"(a failure here means the value was invented, not misplaced)")
    print(f"  cost: ${u['prompt_tokens']*IN_PRICE + u['completion_tokens']*OUT_PRICE:.4f}")
    print("\nNONE of these are gold until a human checks the value against the crop.")
    store.close()


if __name__ == "__main__":
    main()
